version: "3.8"

services:
  mongo:
      image: mongo:6.0
      container_name: mongo
      ports:
        - "27018:27017"  # Mapeia a porta 27018 do host para a porta 27017 do contêiner
      volumes:
        - mongo-data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo  # Garante que o serviço mongo seja iniciado antes do backend
    environment:
      MONGO_URL: mongodb://mongo:27017/ecom-db  # URL de conexão com o MongoDB
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  

volumes:
  mongo-data:
    driver: local
